import { defineField, defineType } from 'sanity';

const fontOptions = {
  list: [
    { title: 'Cormorant Garamond', value: 'editorial' },
    { title: 'Manrope', value: 'sans' },
    { title: 'Georgia', value: 'classic' },
    { title: 'Arial', value: 'arial' },
    { title: 'Roboto', value: 'roboto' },
    { title: 'Inter', value: 'inter' },
    { title: 'Open Sans', value: 'opensans' },
    { title: 'Montserrat', value: 'montserrat' },
    { title: 'Poppins', value: 'poppins' },
    { title: 'DM Sans', value: 'dmsans' },
    { title: 'Lato', value: 'lato' },
    { title: 'Playfair Display', value: 'playfair' },
    { title: 'Lora', value: 'lora' },
    { title: 'Merriweather', value: 'merriweather' },
  ],
  layout: 'dropdown' as const,
};

const alignOptions = {
  list: [
    { title: 'Esquerda', value: 'left' },
    { title: 'Centro', value: 'center' },
    { title: 'Direita', value: 'right' },
  ],
  layout: 'radio' as const,
};

const typographyFields = [
  ['brandName', 'Marca · nome', 'sans', 15, 'left'],
  ['brandSubtitleStyle', 'Marca · subtítulo', 'sans', 12, 'left'],
  ['navStyle', 'Navegação', 'sans', 14, 'left'],
  ['eyebrowStyle', 'Chamadas curtas', 'sans', 12, 'left'],
  ['buttonStyle', 'Botões', 'sans', 14, 'center'],
  ['heroTitle', 'Hero · título', 'editorial', 67, 'left'],
  ['heroDescription', 'Hero · descrição', 'sans', 16, 'left'],
  ['aboutTitle', 'Sobre · título', 'editorial', 56, 'left'],
  ['aboutDescription', 'Sobre · descrição', 'sans', 16, 'left'],
  ['trustTitleStyle', 'Sobre · destaques (título)', 'editorial', 27, 'left'],
  ['trustBodyStyle', 'Sobre · destaques (descrição)', 'sans', 14, 'left'],
  ['treatmentsTitle', 'Tratamentos · título', 'editorial', 56, 'left'],
  ['treatmentsDescription', 'Tratamentos · descrição', 'sans', 16, 'left'],
  ['treatmentCardTitleStyle', 'Tratamentos · cards (título)', 'editorial', 26, 'left'],
  ['treatmentCardBodyStyle', 'Tratamentos · cards (descrição)', 'sans', 16, 'left'],
  ['casesTitle', 'Casos · título', 'editorial', 56, 'left'],
  ['casesDescription', 'Casos · descrição', 'sans', 16, 'left'],
  ['caseLabelStyle', 'Casos · etiqueta', 'sans', 12, 'left'],
  ['caseCardTitleStyle', 'Casos · cards (título)', 'editorial', 26, 'left'],
  ['caseCardBodyStyle', 'Casos · cards (descrição)', 'sans', 16, 'left'],
  ['contactTitle', 'Contato · título', 'editorial', 56, 'left'],
  ['contactDescription', 'Contato · descrição', 'sans', 16, 'left'],
  ['footerStyle', 'Rodapé', 'sans', 14, 'left'],
] as const;

const sectionLayoutFields = [
  ['hero', 'Hero', 100, 0, 0, 32],
  ['about', 'Sobre', 100, 0, 0, 72],
  ['treatments', 'Tratamentos', 100, 0, 0, 72],
  ['cases', 'Casos clínicos', 100, 0, 0, 72],
  ['contact', 'Contato', 100, 0, 0, 72],
] as const;

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Configurações do site',
  type: 'document',
  groups: [
    { name: 'content', title: 'Conteúdo', default: true },
    { name: 'layout', title: 'Layout' },
    { name: 'style', title: 'Estilo' },
    { name: 'seo', title: 'SEO' },
  ],
  initialValue: {
    professionalName: 'Dra. Heloisa Veiga',
    brandSubtitle: 'Odontologia estética · São Paulo',
    whatsapp: '5511987312961',
    instagram: 'https://www.instagram.com/dra.heloisaveiga',
    navAboutLabel: 'Sobre',
    navTreatmentsLabel: 'Tratamentos',
    navCasesLabel: 'Casos',
    navContactLabel: 'Contato',
    heroEyebrow: 'Odontologia estética em São Paulo',
    heroTitle: 'Saúde, beleza e confiança em cada sorriso.',
    heroDescription: 'Formada pela USP, a Dra. Heloisa Veiga atua com foco em odontologia estética e planejamento individualizado, respeitando as características de cada paciente.',
    primaryCtaLabel: 'Agendar avaliação',
    instagramCtaLabel: 'Ver Instagram',
    aboutEyebrow: 'Sobre',
    aboutTitle: 'Estética com naturalidade e cuidado individualizado.',
    aboutDescription: 'Cada tratamento parte de uma avaliação cuidadosa para combinar saúde, função e estética. O objetivo é construir resultados harmônicos, sem perder a identidade do sorriso de cada paciente.',
    trust1Title: 'USP',
    trust1Body: 'Formação acadêmica',
    trust2Title: 'Estética',
    trust2Body: 'Planejamento individualizado',
    trust3Title: 'Naturalidade',
    trust3Body: 'Respeito às características do paciente',
    treatmentsEyebrow: 'Tratamentos',
    treatmentsTitle: 'Tratamentos pensados para cada sorriso.',
    treatmentsDescription: 'Conheça algumas das possibilidades de tratamento e converse com a Dra. Heloisa para entender qual abordagem faz sentido para o seu caso.',
    casesEyebrow: 'Casos clínicos',
    casesTitle: 'Resultados e casos clínicos.',
    casesDescription: 'Casos publicados no CMS aparecem aqui automaticamente. As imagens devem ser usadas sempre com a autorização adequada do paciente.',
    beforeLabel: 'Antes',
    afterLabel: 'Depois',
    contactEyebrow: 'Contato',
    contactTitle: 'Vamos conversar sobre o seu sorriso?',
    contactDescription: 'Entre em contato pelo WhatsApp para tirar dúvidas e agendar uma avaliação.',
    whatsappCtaLabel: 'Falar no WhatsApp',
    mapsCtaLabel: 'Como chegar',
    footerLocation: 'São Paulo, SP',
    sectionOrder: ['hero', 'about', 'treatments', 'cases', 'contact'],
    heroImageWidth: 100,
    heroImageOffsetX: 0,
    heroImageOffsetY: 0,
    heroImageHeight: 450,
    heroImagePositionX: 50,
    heroImagePositionY: 10,
    treatmentImageHeight: 260,
    treatmentImagePositionX: 50,
    treatmentImagePositionY: 50,
    caseImageHeight: 320,
    caseImagePositionX: 50,
    caseImagePositionY: 50,
    seoTitle: 'Dra. Heloisa Veiga | Odontologia Estética em São Paulo',
    seoDescription: 'Odontologia estética com atendimento personalizado em São Paulo. Conheça o trabalho da Dra. Heloisa Veiga e agende uma avaliação.',
  },
  fields: [
    defineField({ name: 'professionalName', title: 'Nome profissional', type: 'string', group: 'content' }),
    defineField({ name: 'brandSubtitle', title: 'Subtítulo da marca', type: 'string', group: 'content' }),
    defineField({ name: 'brandLogo', title: 'Ícone / logo da marca', type: 'image', options: {hotspot: true}, group: 'content', description: 'Substitui o ícone HV no cabeçalho.' }),
    defineField({ name: 'cro', title: 'CRO', type: 'string', group: 'content' }),
    defineField({ name: 'whatsapp', title: 'WhatsApp', type: 'string', group: 'content', description: 'Somente números, com DDI e DDD. Ex.: 5511999999999' }),
    defineField({ name: 'instagram', title: 'Instagram', type: 'url', group: 'content' }),
    defineField({ name: 'clinicAddress', title: 'Endereço da clínica', type: 'string', group: 'content' }),
    defineField({ name: 'mapsUrl', title: 'Link do Google Maps', type: 'url', group: 'content' }),

    defineField({ name: 'navAboutLabel', title: 'Menu · Sobre', type: 'string', group: 'content' }),
    defineField({ name: 'navTreatmentsLabel', title: 'Menu · Tratamentos', type: 'string', group: 'content' }),
    defineField({ name: 'navCasesLabel', title: 'Menu · Casos', type: 'string', group: 'content' }),
    defineField({ name: 'navContactLabel', title: 'Menu · Contato', type: 'string', group: 'content' }),

    defineField({ name: 'heroEyebrow', title: 'Hero · chamada curta', type: 'string', group: 'content' }),
    defineField({ name: 'heroTitle', title: 'Hero · título', type: 'string', group: 'content' }),
    defineField({ name: 'heroDescription', title: 'Hero · descrição', type: 'text', rows: 4, group: 'content' }),
    defineField({ name: 'heroImage', title: 'Hero · foto principal', type: 'image', options: { hotspot: true }, group: 'content' }),
    defineField({ name: 'primaryCtaLabel', title: 'Hero · botão WhatsApp', type: 'string', group: 'content' }),
    defineField({ name: 'instagramCtaLabel', title: 'Hero · botão Instagram', type: 'string', group: 'content' }),

    defineField({ name: 'aboutEyebrow', title: 'Sobre · chamada curta', type: 'string', group: 'content' }),
    defineField({ name: 'aboutTitle', title: 'Sobre · título', type: 'string', group: 'content' }),
    defineField({ name: 'aboutDescription', title: 'Sobre · descrição', type: 'text', rows: 5, group: 'content' }),
    defineField({ name: 'trust1Title', title: 'Sobre · destaque 1 · título', type: 'string', group: 'content' }),
    defineField({ name: 'trust1Body', title: 'Sobre · destaque 1 · descrição', type: 'string', group: 'content' }),
    defineField({ name: 'trust2Title', title: 'Sobre · destaque 2 · título', type: 'string', group: 'content' }),
    defineField({ name: 'trust2Body', title: 'Sobre · destaque 2 · descrição', type: 'string', group: 'content' }),
    defineField({ name: 'trust3Title', title: 'Sobre · destaque 3 · título', type: 'string', group: 'content' }),
    defineField({ name: 'trust3Body', title: 'Sobre · destaque 3 · descrição', type: 'string', group: 'content' }),

    defineField({ name: 'treatmentsEyebrow', title: 'Tratamentos · chamada curta', type: 'string', group: 'content' }),
    defineField({ name: 'treatmentsTitle', title: 'Tratamentos · título da seção', type: 'string', group: 'content' }),
    defineField({ name: 'treatmentsDescription', title: 'Tratamentos · descrição da seção', type: 'text', rows: 3, group: 'content' }),
    defineField({ name: 'casesEyebrow', title: 'Casos · chamada curta', type: 'string', group: 'content' }),
    defineField({ name: 'casesTitle', title: 'Casos · título da seção', type: 'string', group: 'content' }),
    defineField({ name: 'casesDescription', title: 'Casos · descrição da seção', type: 'text', rows: 3, group: 'content' }),
    defineField({ name: 'beforeLabel', title: 'Casos · etiqueta Antes', type: 'string', group: 'content' }),
    defineField({ name: 'afterLabel', title: 'Casos · etiqueta Depois', type: 'string', group: 'content' }),

    defineField({ name: 'contactEyebrow', title: 'Contato · chamada curta', type: 'string', group: 'content' }),
    defineField({ name: 'contactTitle', title: 'Contato · título', type: 'string', group: 'content' }),
    defineField({ name: 'contactDescription', title: 'Contato · descrição', type: 'text', rows: 3, group: 'content' }),
    defineField({ name: 'whatsappCtaLabel', title: 'Contato · botão WhatsApp', type: 'string', group: 'content' }),
    defineField({ name: 'mapsCtaLabel', title: 'Contato · botão mapa', type: 'string', group: 'content' }),
    defineField({ name: 'footerLocation', title: 'Rodapé · localização', type: 'string', group: 'content' }),

    defineField({
      name: 'sectionOrder', title: 'Ordem das seções', description: 'Também pode ser alterada arrastando as seções no Construtor visual.', type: 'array', of: [{ type: 'string' }],
      options: {list: [
        { title: 'Hero', value: 'hero' }, { title: 'Sobre', value: 'about' }, { title: 'Tratamentos', value: 'treatments' }, { title: 'Casos clínicos', value: 'cases' }, { title: 'Contato', value: 'contact' },
      ]},
      validation: (Rule) => Rule.unique().min(5).max(5), group: 'layout',
    }),

    ...sectionLayoutFields.flatMap(([key, label, width, x, y, padding]) => [
      defineField({ name: `${key}Width`, title: `${label} · largura`, type: 'number', initialValue: width, validation: (Rule) => Rule.min(60).max(100), group: 'layout' }),
      defineField({ name: `${key}OffsetX`, title: `${label} · posição horizontal`, type: 'number', initialValue: x, validation: (Rule) => Rule.min(-100).max(100), group: 'layout' }),
      defineField({ name: `${key}OffsetY`, title: `${label} · posição vertical`, type: 'number', initialValue: y, validation: (Rule) => Rule.min(-80).max(80), group: 'layout' }),
      defineField({ name: `${key}PaddingY`, title: `${label} · espaçamento vertical`, type: 'number', initialValue: padding, validation: (Rule) => Rule.min(16).max(160), group: 'layout' }),
      defineField({ name: `${key}Background`, title: `${label} · cor de fundo`, type: 'string', description: 'Cor hexadecimal, ex.: #ffffff', validation: (Rule) => Rule.regex(/^#[0-9a-fA-F]{6}$/).warning('Use o formato #RRGGBB'), group: 'style' }),
    ]),

    defineField({ name: 'heroImageWidth', title: 'Hero · largura da imagem', type: 'number', initialValue: 100, validation: (Rule) => Rule.min(60).max(100), group: 'layout' }),
    defineField({ name: 'heroImageOffsetX', title: 'Hero · deslocamento horizontal da imagem', type: 'number', initialValue: 0, validation: (Rule) => Rule.min(-100).max(100), group: 'layout' }),
    defineField({ name: 'heroImageOffsetY', title: 'Hero · deslocamento vertical da imagem', type: 'number', initialValue: 0, validation: (Rule) => Rule.min(-80).max(80), group: 'layout' }),
    defineField({ name: 'heroImageHeight', title: 'Hero · altura da imagem', type: 'number', initialValue: 450, validation: (Rule) => Rule.min(260).max(720), group: 'layout' }),
    defineField({ name: 'heroImagePositionX', title: 'Hero · foco horizontal da imagem', type: 'number', initialValue: 50, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),
    defineField({ name: 'heroImagePositionY', title: 'Hero · foco vertical da imagem', type: 'number', initialValue: 10, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),
    defineField({ name: 'treatmentImageHeight', title: 'Tratamentos · altura das imagens', type: 'number', initialValue: 260, validation: (Rule) => Rule.min(160).max(460), group: 'layout' }),
    defineField({ name: 'treatmentImagePositionX', title: 'Tratamentos · foco horizontal', type: 'number', initialValue: 50, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),
    defineField({ name: 'treatmentImagePositionY', title: 'Tratamentos · foco vertical', type: 'number', initialValue: 50, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),
    defineField({ name: 'caseImageHeight', title: 'Casos · altura das imagens', type: 'number', initialValue: 320, validation: (Rule) => Rule.min(180).max(520), group: 'layout' }),
    defineField({ name: 'caseImagePositionX', title: 'Casos · foco horizontal', type: 'number', initialValue: 50, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),
    defineField({ name: 'caseImagePositionY', title: 'Casos · foco vertical', type: 'number', initialValue: 50, validation: (Rule) => Rule.min(0).max(100), group: 'layout' }),

    ...typographyFields.flatMap(([key, label, defaultFont, defaultSize, defaultAlign]) => [
      defineField({ name: `${key}Font`, title: `${label} · fonte`, type: 'string', options: fontOptions, initialValue: defaultFont, group: 'style' }),
      defineField({ name: `${key}Size`, title: `${label} · tamanho`, type: 'number', initialValue: defaultSize, validation: (Rule) => Rule.min(10).max(110), group: 'style' }),
      defineField({ name: `${key}Align`, title: `${label} · alinhamento`, type: 'string', options: alignOptions, initialValue: defaultAlign, group: 'style' }),
      defineField({ name: `${key}Color`, title: `${label} · cor do texto`, type: 'string', description: 'Cor hexadecimal, ex.: #2b2621', validation: (Rule) => Rule.regex(/^#[0-9a-fA-F]{6}$/).warning('Use o formato #RRGGBB'), group: 'style' }),
    ]),

    defineField({ name: 'seoTitle', title: 'Título SEO', type: 'string', group: 'seo' }),
    defineField({ name: 'seoDescription', title: 'Descrição SEO', type: 'text', rows: 3, group: 'seo' }),
  ],
});
